<?php

return [

    /*
     * Global (platform-level) roles. These get tenant_id = null and are
     * assigned to platform staff, not company users.
     */
    'global_roles' => [
        'Super Admin',
        'Support Admin',
    ],

    /*
     * Roles provisioned into every new tenant. Each tenant gets its own
     * copies of these roles (team-scoped via tenant_id) so future
     * per-tenant customization is possible without touching other tenants.
     */
    'tenant_roles' => [
        'Company Owner',
        'Company Admin',
        'Branch Manager',
        'HR Manager',
        'HR Officer',
        'Operations Manager',
        'Clearing Officer',
        'Forwarding Officer',
        'Warehouse Manager',
        'Warehouse Staff',
        'Dispatcher',
        'Fleet Manager',
        'Transport Coordinator',
        'Driver',
        'Finance Manager',
        'Accountant',
        'Cashier',
        'Sales Manager',
        'Sales Executive',
        'Customer Service',
        'Document Controller',
        'Auditor',
        'Customer Portal User',
        'Employee',
    ],

    /*
     * Permission catalog, grouped by module. Each future ERP module
     * (crm, shipments, clearing, ...) adds its own entry here without
     * touching this structure.
     */
    'permissions' => [
        'platform' => [
            'platform.tenants.view' => 'View tenants',
            'platform.tenants.manage' => 'Suspend / activate tenants',
            'platform.plans.view' => 'View subscription plans',
            'platform.plans.manage' => 'Create / edit / delete subscription plans',
            'platform.subscriptions.view' => 'View tenant subscriptions',
            'platform.metrics.view' => 'View platform-wide metrics',
            'platform.audit.view' => 'View platform audit log',
            'platform.support.manage' => 'Manage support tickets',
            'platform.landing_content.view' => 'View landing page content',
            'platform.landing_content.manage' => 'Edit landing page content',
        ],
        'core' => [
            'core.dashboard.view' => 'View tenant dashboard',
            'core.company.view' => 'View company profile',
            'core.company.manage' => 'Edit company profile',
            'core.branches.view' => 'View branches',
            'core.branches.manage' => 'Create / edit branches',
            'core.users.view' => 'View company users',
            'core.users.manage' => 'Invite / edit / deactivate company users',
            'core.audit.view' => 'View company audit log',
            'core.backup.manage' => 'Export and restore a full backup of the company\'s data',
        ],
        'crm' => [
            'crm.leads.view' => 'View leads',
            'crm.leads.manage' => 'Create / edit / delete / convert leads',
            'crm.customers.view' => 'View customers',
            'crm.customers.manage' => 'Create / edit / delete customers',
            'crm.contacts.view' => 'View customer contacts',
            'crm.contacts.manage' => 'Create / edit / delete customer contacts',
            'crm.compliance.view' => 'View customer compliance/KYC documents',
            'crm.compliance.manage' => 'Upload / edit / delete customer compliance/KYC documents',
        ],
        'clearing' => [
            'clearing.files.view' => 'View clearing files',
            'clearing.files.manage' => 'Create / edit / delete clearing files',
        ],
        'freight' => [
            'freight.bookings.view' => 'View freight bookings',
            'freight.bookings.manage' => 'Create / edit / delete freight bookings',
        ],
        'containers' => [
            'containers.items.view' => 'View containers',
            'containers.items.manage' => 'Create / edit / delete containers',
        ],
        'warehouse' => [
            'warehouse.items.view' => 'View warehouse items',
            'warehouse.items.manage' => 'Create / edit / delete warehouse items',
        ],
        'fleet' => [
            'fleet.vehicles.view' => 'View fleet vehicles',
            'fleet.vehicles.manage' => 'Create / edit / delete fleet vehicles',
        ],
        'finance' => [
            'finance.invoices.view' => 'View invoices',
            'finance.invoices.manage' => 'Create / edit / delete invoices',
            'finance.exchange_rates.view' => 'View exchange rate history',
            'finance.exchange_rates.manage' => 'Record / delete exchange rates',
        ],
        'accounting' => [
            'accounting.accounts.view' => 'View chart of accounts',
            'accounting.accounts.manage' => 'Create / edit / delete accounts',
            'accounting.journal.view' => 'View journal entries',
            'accounting.journal.manage' => 'Create / edit / delete draft journal entries',
            'accounting.journal.post' => 'Post / void journal entries',
        ],
        'documents' => [
            'documents.files.view' => 'View documents',
            'documents.files.manage' => 'Upload / delete documents',
        ],
        'reports' => [
            'reports.view' => 'View cross-module reports',
            'reports.manage' => 'Create / edit / delete scheduled report emails',
        ],
        'analytics' => [
            'analytics.view' => 'View operational & financial analytics',
        ],
        'quotations' => [
            'quotations.items.view' => 'View quotations',
            'quotations.items.manage' => 'Create / edit / delete quotations',
            'quotations.items.approve' => 'Approve or reject quotations submitted for pricing sign-off',
        ],
        'shipments' => [
            'shipments.items.view' => 'View shipments',
            'shipments.items.manage' => 'Create / edit / delete shipments',
            'shipments.costs.view' => 'View shipment revenue, cost and profit margin',
        ],
        'portal' => [
            'portal.access' => 'Access the client portal (own company data only)',
            'portal.documents.upload' => 'Upload documents via the client portal',
            'portal.quotations.approve' => 'Approve / reject quotations via the client portal',
            'portal.messages.send' => 'Send messages via the client portal',
            'portal.api_keys.manage' => 'Generate / revoke Client API keys via the client portal',
        ],
        'demurrage' => [
            'demurrage.rate_cards.view' => 'View demurrage rate cards',
            'demurrage.rate_cards.manage' => 'Create / edit / delete demurrage rate cards',
            'demurrage.charges.view' => 'View demurrage dashboard & charge history',
            'demurrage.charges.manage' => 'Calculate / waive / invoice demurrage charges',
        ],
        'detention' => [
            'detention.rate_cards.view' => 'View detention rate cards',
            'detention.rate_cards.manage' => 'Create / edit / delete detention rate cards',
            'detention.charges.view' => 'View detention dashboard & charge history',
            'detention.charges.manage' => 'Calculate / waive / invoice detention charges',
        ],
        'expenses' => [
            'expenses.items.view' => 'View expenses',
            'expenses.items.manage' => 'Create / edit / delete / submit / mark expenses paid',
            'expenses.items.approve' => 'Approve or reject submitted expenses',
        ],
        'workflows' => [
            'workflows.definitions.view' => 'View approval workflow definitions',
            'workflows.definitions.manage' => 'Create / edit / delete approval workflow definitions',
        ],
        'hr' => [
            'hr.departments.view' => 'View departments',
            'hr.departments.manage' => 'Create / edit / delete departments',
            'hr.designations.view' => 'View job designations',
            'hr.designations.manage' => 'Create / edit / archive job designations',
            'hr.employees.view' => 'View employees',
            'hr.employees.manage' => 'Create / edit / delete employees',
            'hr.employees.salary.view' => 'View employee salary and bank details',
            'hr.employees.documents.view' => 'View employee documents',
            'hr.employees.documents.manage' => 'Upload / verify / reject employee documents',
            'hr.contracts.view' => 'View employee contracts',
            'hr.contracts.manage' => 'Create / edit / submit employee contracts',
            'hr.contracts.approve' => 'Approve or reject employee contracts (legacy fallback when no workflow applies)',
            'hr.attendance.view' => 'View attendance records',
            'hr.attendance.manage' => 'Create / edit / delete attendance records, manage public holidays, bulk-import attendance',
            'hr.shifts.view' => 'View shifts and shift assignments',
            'hr.shifts.manage' => 'Create / edit / delete shifts and assign employees to them',
            'hr.timesheets.view' => 'View timesheets',
            'hr.timesheets.manage' => 'Create / edit / delete timesheets',
            'hr.timesheets.approve' => 'Approve or reject submitted timesheets',
            'hr.leave.view' => 'View leave types, balances and requests',
            'hr.leave.manage' => 'Create leave requests, manage leave types, cancel requests',
            'hr.leave.approve' => 'Approve or reject leave requests (legacy fallback when no workflow applies)',
            'hr.payroll_components.view' => 'View payroll components (earnings, deductions, employer contributions) and employee assignments',
            'hr.payroll_components.manage' => 'Create / edit / delete payroll components and assign them to employees',
            'hr.statutory_rules.view' => 'View statutory rule sets, tax bands and contribution rules',
            'hr.statutory_rules.manage' => 'Create / edit / delete statutory rule sets, tax bands and contribution rules',
            'hr.payroll_settings.view' => 'View payroll settings and chart-of-account mappings',
            'hr.payroll_settings.manage' => 'Edit payroll settings and chart-of-account mappings',
            'hr.payroll_periods.view' => 'View payroll periods',
            'hr.payroll_periods.manage' => 'Create / delete payroll periods',
            'hr.payroll_runs.view' => 'View payroll runs and their calculated results',
            'hr.payroll_runs.manage' => 'Create, calculate and submit payroll runs for approval',
            'hr.payroll_runs.approve' => 'Approve, reject and finalize payroll runs (legacy fallback when no workflow applies)',
            'hr.loans.view' => 'View employee loans and repayment schedules',
            'hr.loans.manage' => 'Create, submit and delete employee loans',
            'hr.loans.approve' => 'Approve or reject employee loans (legacy fallback when no workflow applies)',
            'hr.advances.view' => 'View salary advances and repayment schedules',
            'hr.advances.manage' => 'Create, submit and delete salary advances',
            'hr.advances.approve' => 'Approve or reject salary advances (legacy fallback when no workflow applies)',
            'hr.overtime.view' => 'View overtime requests',
            'hr.overtime.manage' => 'Create and delete overtime requests',
            'hr.overtime.approve' => 'Approve or reject overtime requests',
            'hr.payslips.view.all' => 'View any employee\'s payslips (without this, a user only sees their own)',
            'hr.performance.view.all' => 'View any employee\'s performance reviews (without this, a user only sees their own)',
            'hr.performance.manage' => 'Create, submit and delete performance reviews',
            'hr.disciplinary.view' => 'View disciplinary records',
            'hr.disciplinary.manage' => 'Create, acknowledge and resolve disciplinary records',
            'hr.assets.view' => 'View employee asset assignments',
            'hr.assets.manage' => 'Assign and process returns of employee assets',
            'hr.exits.view' => 'View employee exit records',
            'hr.exits.manage' => 'Initiate, update and complete employee exit records',
            'hr.recruitment.view' => 'View job vacancies, candidates and applications',
            'hr.recruitment.manage' => 'Create and manage job vacancies, candidates, applications, interviews, and hire candidates',
            'hr.onboarding.view' => 'View employee onboarding checklists',
            'hr.onboarding.manage' => 'Manage onboarding checklist tasks',
        ],
        'identity' => [
            'identity.verify' => 'Submit an employee identity for verification',
            'identity.confirm' => 'Confirm or reject a returned identity verification match',
            'identity.reject' => 'Reject a returned identity verification match',
            'identity.view' => 'View identity verification status, results and history',
            'identity.manual-review.create' => 'Submit an identity for manual review',
            'identity.manual-review.approve' => 'Approve a manual identity review',
            'identity.manual-review.reject' => 'Reject a manual identity review',
            'identity.override' => 'Manually override identity-sourced employee fields',
            'identity.audit.view' => 'View identity verification audit history',
            'identity.resync' => 'Request identity re-verification for an existing employee',
            'identity.settings.manage' => 'Manage identity verification provider settings',
        ],
        'ai' => [
            'ai.assistant.use' => 'Use the AI assistant',
            'ai.email_parser.use' => 'Use the AI email parser',
        ],
    ],

    /*
     * Default permissions granted to each role at seed/provisioning time.
     * Wildcards ('platform.*', 'core.*') expand to every permission in
     * that module's catalog above.
     */
    'default_role_permissions' => [
        'Super Admin' => ['platform.*'],
        'Support Admin' => [
            'platform.tenants.view',
            'platform.support.manage',
            'platform.audit.view',
            'platform.metrics.view',
        ],

        'Company Owner' => ['core.*', 'crm.*', 'clearing.*', 'freight.*', 'containers.*', 'warehouse.*', 'fleet.*', 'finance.*', 'accounting.*', 'documents.*', 'reports.*', 'quotations.*', 'shipments.*', 'analytics.*', 'demurrage.*', 'detention.*', 'expenses.*', 'workflows.*', 'hr.*', 'identity.*', 'ai.*'],
        'Company Admin' => ['core.*', 'crm.*', 'clearing.*', 'freight.*', 'containers.*', 'warehouse.*', 'fleet.*', 'finance.*', 'accounting.*', 'documents.*', 'reports.*', 'quotations.*', 'shipments.*', 'analytics.*', 'demurrage.*', 'detention.*', 'expenses.*', 'workflows.*', 'hr.*', 'identity.*', 'ai.*'],
        'Branch Manager' => ['core.dashboard.view', 'core.branches.view', 'core.users.view', 'hr.*'],
        'HR Manager' => [
            'core.dashboard.view', 'core.users.view', 'hr.*',
            'identity.verify', 'identity.view', 'identity.confirm', 'identity.reject',
            'identity.manual-review.create', 'identity.manual-review.approve', 'identity.manual-review.reject',
            'identity.resync',
        ],
        'HR Officer' => [
            'core.dashboard.view',
            'hr.departments.view',
            'hr.designations.view',
            'hr.employees.view', 'hr.employees.manage',
            'hr.employees.documents.view', 'hr.employees.documents.manage',
            'hr.contracts.view', 'hr.contracts.manage',
            'hr.attendance.view', 'hr.attendance.manage',
            'hr.shifts.view', 'hr.shifts.manage',
            'hr.timesheets.view', 'hr.timesheets.manage',
            'hr.leave.view', 'hr.leave.manage',
            'hr.payroll_components.view',
            'hr.statutory_rules.view',
            'hr.loans.view', 'hr.loans.manage',
            'hr.advances.view', 'hr.advances.manage',
            'hr.overtime.view', 'hr.overtime.manage', 'hr.overtime.approve',
            'hr.payslips.view.all',
            'hr.performance.view.all', 'hr.performance.manage',
            'hr.disciplinary.view', 'hr.disciplinary.manage',
            'hr.assets.view', 'hr.assets.manage',
            'hr.exits.view', 'hr.exits.manage',
            'hr.recruitment.view', 'hr.recruitment.manage',
            'hr.onboarding.view', 'hr.onboarding.manage',
            'identity.verify', 'identity.view', 'identity.confirm', 'identity.reject', 'identity.manual-review.create',
        ],
        'Operations Manager' =>['core.dashboard.view', 'core.branches.view', 'clearing.files.view', 'freight.bookings.view', 'containers.items.view', 'warehouse.items.view', 'fleet.vehicles.view', 'finance.invoices.view', 'accounting.accounts.view', 'accounting.journal.view', 'documents.files.view', 'reports.view', 'quotations.items.view', 'shipments.*', 'analytics.view', 'demurrage.charges.view', 'demurrage.charges.manage', 'detention.charges.view', 'detention.charges.manage', 'expenses.items.view', 'expenses.items.manage'],
        'Clearing Officer' => ['core.dashboard.view', 'clearing.files.view', 'clearing.files.manage', 'containers.items.view', 'containers.items.manage', 'shipments.items.view', 'demurrage.charges.view', 'demurrage.charges.manage', 'detention.charges.view', 'detention.charges.manage', 'expenses.items.view', 'expenses.items.manage'],
        'Forwarding Officer' => ['core.dashboard.view', 'freight.bookings.view', 'freight.bookings.manage', 'containers.items.view', 'containers.items.manage', 'shipments.items.view', 'expenses.items.view', 'expenses.items.manage'],
        'Warehouse Manager' => ['core.dashboard.view', 'containers.items.view', 'containers.items.manage', 'warehouse.items.view', 'warehouse.items.manage', 'demurrage.charges.view', 'demurrage.charges.manage', 'detention.charges.view', 'detention.charges.manage', 'expenses.items.view', 'expenses.items.manage'],
        'Warehouse Staff' => ['core.dashboard.view', 'containers.items.view', 'containers.items.manage', 'warehouse.items.view', 'warehouse.items.manage'],
        'Dispatcher' => ['core.dashboard.view', 'fleet.vehicles.view'],
        'Fleet Manager' => ['core.dashboard.view', 'fleet.vehicles.view', 'fleet.vehicles.manage'],
        'Transport Coordinator' => ['core.dashboard.view', 'fleet.vehicles.view', 'fleet.vehicles.manage', 'freight.bookings.view', 'freight.bookings.manage', 'containers.items.view', 'containers.items.manage', 'shipments.items.view'],
        'Driver' => ['core.dashboard.view', 'fleet.vehicles.view'],
        'Finance Manager' => ['core.dashboard.view', 'finance.invoices.view', 'finance.invoices.manage', 'finance.exchange_rates.view', 'finance.exchange_rates.manage', 'accounting.*', 'reports.view', 'analytics.view', 'demurrage.*', 'detention.*', 'expenses.*', 'workflows.*', 'shipments.items.view', 'shipments.costs.view', 'hr.payroll_components.view', 'hr.statutory_rules.view', 'hr.payroll_settings.view', 'hr.payroll_settings.manage', 'hr.payroll_periods.view', 'hr.payroll_runs.view', 'hr.payroll_runs.approve', 'hr.loans.view', 'hr.loans.approve', 'hr.advances.view', 'hr.advances.approve', 'hr.payslips.view.all', 'identity.view'],
        'Accountant' => ['core.dashboard.view', 'finance.invoices.view', 'finance.invoices.manage', 'finance.exchange_rates.view', 'finance.exchange_rates.manage', 'accounting.accounts.view', 'accounting.accounts.manage', 'accounting.journal.view', 'accounting.journal.manage', 'expenses.items.view', 'expenses.items.manage', 'shipments.items.view', 'shipments.costs.view'],
        'Cashier' => ['core.dashboard.view', 'finance.invoices.view', 'finance.invoices.manage', 'finance.exchange_rates.view', 'expenses.items.view', 'expenses.items.manage', 'reports.view'],
        'Sales Manager' => ['core.dashboard.view', 'crm.*', 'quotations.*', 'ai.email_parser.use'],
        'Sales Executive' => [
            'core.dashboard.view',
            'crm.leads.view', 'crm.leads.manage',
            'crm.customers.view', 'crm.customers.manage',
            'crm.contacts.view', 'crm.contacts.manage',
            'crm.compliance.view', 'crm.compliance.manage',
            'quotations.items.view', 'quotations.items.manage',
            'ai.email_parser.use',
        ],
        'Customer Service' => [
            'core.dashboard.view',
            'crm.leads.view',
            'crm.customers.view',
            'crm.contacts.view', 'crm.contacts.manage',
            'crm.compliance.view',
            'quotations.items.view',
        ],
        'Document Controller' => ['core.dashboard.view', 'documents.files.view', 'documents.files.manage'],
        'Auditor' => [
            'core.dashboard.view',
            'core.audit.view',
            'core.company.view',
            'core.branches.view',
            'core.users.view',
            'crm.leads.view',
            'crm.customers.view',
            'crm.contacts.view',
            'crm.compliance.view',
            'clearing.files.view',
            'freight.bookings.view',
            'containers.items.view',
            'warehouse.items.view',
            'fleet.vehicles.view',
            'finance.invoices.view',
            'accounting.accounts.view',
            'accounting.journal.view',
            'documents.files.view',
            'reports.view',
            'quotations.items.view',
            'shipments.items.view',
            'shipments.costs.view',
            'analytics.view',
            'demurrage.rate_cards.view',
            'demurrage.charges.view',
            'detention.rate_cards.view',
            'detention.charges.view',
            'expenses.items.view',
            'workflows.definitions.view',
            'hr.departments.view',
            'hr.employees.view',
            'hr.attendance.view',
            'identity.view',
            'identity.audit.view',
        ],
        'Customer Portal User' => ['portal.access', 'portal.documents.upload', 'portal.quotations.approve', 'portal.messages.send', 'portal.api_keys.manage'],

        // Deliberately empty: a restricted self-service role with none of the
        // broad hr.* view/manage permissions. Reaches its own profile,
        // attendance, leave, payslips, performance reviews and assets
        // exclusively through the permission-free "my/*" self-service
        // endpoints (Employee.user_id === Auth::id() ownership check inside
        // each controller), the same model already used for payslips/
        // performance reviews.
        'Employee' => [],
    ],
];
